# Commercium E-commerce Platform Configuration
environment: development
version: "v0.2.0"

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  tls:
    enabled: false
    cert_file: ""
    key_file: ""

database:
  host: "localhost"
  port: 5432
  user: "commercium_user"
  password: "commercium_password"
  database: "commercium_db"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 10
  max_lifetime: 30m
  max_idle_time: 15m

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  max_retries: 3
  pool_size: 10
  min_idle_conns: 5
  pool_timeout: 30s
  idle_timeout: 5m
  read_timeout: 3s
  write_timeout: 3s

kafka:
  brokers:
    - "localhost:9092"
  consumer_group: "commercium-consumers"
  batch_size: 100
  batch_timeout: 1s
  retry_max: 3
  topics:
    user_events: "user.events"
    product_events: "product.events"
    order_events: "order.events"
    payment_events: "payment.events"
    inventory_events: "inventory.events"

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  exchange: "commercium.exchange"
  exchange_type: "topic"
  retry_max: 3
  retry_delay: 5s
  queues:
    email_notifications: "notifications.email"
    sms_notifications: "notifications.sms"
    payment_processing: "payments.processing"
    order_processing: "orders.processing"
    inventory_updates: "inventory.updates"

auth:
  jwt:
    secret_key: "your-super-secret-jwt-key-change-this-in-production"
    issuer: "commercium"
    expiration: 15m
    refresh_expiration: 24h
  oauth2:
    enabled: false
    google_client_id: ""
    google_client_secret: ""
    github_client_id: ""
    github_client_secret: ""

logger:
  level: "info"
  format: "json"
  output: "stdout"
  filename: ""
  max_size: 100
  max_backups: 3
  max_age: 28

metrics:
  enabled: true
  path: "/metrics"
  port: 9090
  namespace: "commercium"
  subsystem: "api_gateway"

tracing:
  enabled: true
  service_name: "api-gateway"
  jaeger:
    endpoint: "http://localhost:14268/api/traces"
    agent_host: "localhost"
    agent_port: 6831
  sampling_rate: 1.0

vault:
  enabled: false
  address: "http://localhost:8200"
  token: ""
  mount_path: "secret"
