# Development Environment Configuration
environment: development
version: "v0.1.0"

server:
  port: 8080
  host: "localhost"
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 60s
  tls:
    enabled: false
    cert_file: ""
    key_file: ""

database:
  host: localhost
  port: 5432
  user: postgres
  password: password
  database: ecommerce
  ssl_mode: disable
  max_open_conns: 25
  max_idle_conns: 10
  max_lifetime: 300s
  max_idle_time: 60s

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  max_retries: 3
  pool_size: 10
  min_idle_conns: 2
  pool_timeout: 30s
  idle_timeout: 300s

kafka:
  brokers:
    - localhost:9092
  consumer_group: ecommerce-platform
  batch_size: 100
  batch_timeout: 1s
  retry_max: 3
  topics:
    user_events: user.events
    product_events: product.events
    order_events: order.events
    payment_events: payment.events
    inventory_events: inventory.events

rabbitmq:
  url: amqp://admin:password@localhost:5672/
  exchange: ecommerce.tasks
  exchange_type: topic
  retry_max: 3
  retry_delay: 5s
  queues:
    email_notifications: email.notifications
    sms_notifications: sms.notifications
    payment_processing: payment.processing
    order_processing: order.processing
    inventory_updates: inventory.updates

auth:
  jwt:
    secret_key: dev-secret-key-change-in-production
    issuer: ecommerce-platform
    expiration: 24h
    refresh_expiration: 168h # 7 days
  oauth2:
    enabled: false
    google_client_id: ""
    google_client_secret: ""
    github_client_id: ""
    github_client_secret: ""

logger:
  level: debug
  format: json
  output: stdout
  filename: ""
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true

metrics:
  enabled: true
  path: /metrics
  namespace: ecommerce
  subsystem: ""

tracing:
  enabled: true
  service_name: ""
  endpoint: http://localhost:14268/api/traces
  sample_rate: 1.0

vault:
  address: http://localhost:8200
  token: dev-token
  namespace: ""
  auth_method: token
  role: ""
  secret_path: secret/ecommerce

# Service-specific configurations
services:
  api_gateway:
    port: 8080
    graphql:
      playground_enabled: true
      introspection_enabled: true
      complexity_limit: 1000
      depth_limit: 10
    rate_limiting:
      enabled: true
      requests_per_minute: 1000
      burst: 100
    cors:
      allowed_origins: ["*"]
      allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allowed_headers: ["*"]

  user_service:
    port: 8081
    password:
      min_length: 8
      require_uppercase: true
      require_lowercase: true
      require_numbers: true
      require_special: true
    session:
      timeout: 24h
      cleanup_interval: 1h

  product_service:
    port: 8082
    elasticsearch:
      url: http://localhost:9200
      index: products
      shards: 1
      replicas: 0
    cache:
      ttl: 300s
      max_size: 10000

  order_service:
    port: 8083
    timeout:
      create: 30s
      payment: 300s
      fulfillment: 3600s
    saga:
      timeout: 600s
      retry_attempts: 3

  payment_service:
    port: 8084
    providers:
      stripe:
        enabled: false
        public_key: ""
        secret_key: ""
        webhook_secret: ""
      paypal:
        enabled: false
        client_id: ""
        client_secret: ""
    timeout: 30s

  inventory_service:
    port: 8085
    low_stock_threshold: 10
    reorder_threshold: 5
    batch_update_size: 100
    sync_interval: 60s

  notification_service:
    port: 8086
    email:
      smtp_host: localhost
      smtp_port: 587
      smtp_user: ""
      smtp_password: ""
      from_address: noreply@ecommerce.com
      from_name: E-Commerce Platform
    sms:
      provider: twilio
      account_sid: ""
      auth_token: ""
      from_number: ""
    push:
      provider: fcm
      server_key: ""
    templates:
      path: ./templates
      cache_enabled: true
